api = "0.2"

[buildpack]
id = "org.cloudfoundry.php-dist"
name = "PHP Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
php-binary = "7.2.*"


[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
source = "https://php.net/distributions/php-5.6.9.tar.gz"
version = "5.6.9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://github.com/pepabo/binary-builder/releases/download/v0.0.1/php-5.6.9-linux-x64.tgz"
sha256 = "777b0067594f20d52845e4f87033933158a5c9d87bbd17c970a47de51a024485"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "1e7fe73b4969d3922fd6beb7c9f8921d4ffdceb4a1f123e030e95645845a975c"
source = "https://php.net/distributions/php-7.1.31.tar.gz"
source_sha256 = "ea0558735653b9ce63e9cea41dd8f0d0b90dba6c39d39dd9a6aad5cc58b0bdfc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.31-linux-x64-cflinuxfs3-1e7fe73b.tgz"
version = "7.1.31"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "644ed4cfccb1a3be393807cf07fefe9bfeab477501629c44509b1a52063555ee"
source = "https://php.net/distributions/php-7.1.32.tar.gz"
source_sha256 = "6e51a2fc610352438b2a1c40310468a1e2b5baf2fff43be77f9f408a9111590c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.32-linux-x64-cflinuxfs3-644ed4cf.tgz"
version = "7.1.32"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "f5eae7704a2e8fd3eecff85850c6f302ce8e7da73cb75e56ff64a65c60779195"
source = "https://php.net/distributions/php-7.2.21.tar.gz"
source_sha256 = "8327682bee4a8fd2edf5bbfcc393d986b945bec433fc74458d05e766701b313c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.21-linux-x64-cflinuxfs3-f5eae770.tgz"
version = "7.2.21"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "c9315fce7090db3c26d5823d5ed60a1851864dc44fda5dfe50998862c9d2219b"
source = "https://php.net/distributions/php-7.2.22.tar.gz"
source_sha256 = "6e2ccc77484c27971d4550b7071a57b79bc910bfb2d4a74a57ae2c18b78c3dc7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.22-linux-x64-cflinuxfs3-c9315fce.tgz"
version = "7.2.22"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "6b2c296c32a8f67606a65fbbbe2fdce302936538bca892d9fb60e4d901a4d592"
source = "https://php.net/distributions/php-7.3.8.tar.gz"
source_sha256 = "31af3eff3337fb70733c9b02a3444c3dae662ecab20aeec7fdc3c42e22071490"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.8-linux-x64-cflinuxfs3-6b2c296c.tgz"
version = "7.3.8"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "2e2f589403ee293602c63e231004c84ad6cba541b32eb0ae0256876e9dc43107"
source = "https://php.net/distributions/php-7.3.9.tar.gz"
source_sha256 = "5ecc1b1ad7228ed2e99a970c45358871644fcab1d9fd079a7b129326a7bde42d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.9-linux-x64-cflinuxfs3-2e2f5894.tgz"
version = "7.3.9"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.1.\\d+"
name = "php"
version_line = "7.1.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-11-30T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.2.\\d+"
name = "php"
version_line = "7.2.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.3.\\d+"
name = "php"
version_line = "7.3.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "5.6.\\d+"
name = "php"
version_line = "5.6.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
