api = "0.2"

[buildpack]
id = "org.cloudfoundry.php-dist"
name = "PHP Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
php-binary = "7.2.*"


[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
source = "https://php.net/distributions/php-5.6.9.tar.gz"
version = "5.6.9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://github.com/pepabo/binary-builder/releases/download/v0.0.1/php-5.6.9-linux-x64.tgz"
sha256 = "777b0067594f20d52845e4f87033933158a5c9d87bbd17c970a47de51a024485"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "1e7fe73b4969d3922fd6beb7c9f8921d4ffdceb4a1f123e030e95645845a975c"
source = "https://php.net/distributions/php-7.1.31.tar.gz"
source_sha256 = "ea0558735653b9ce63e9cea41dd8f0d0b90dba6c39d39dd9a6aad5cc58b0bdfc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.31-linux-x64-cflinuxfs3-1e7fe73b.tgz"
version = "7.1.31"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "644ed4cfccb1a3be393807cf07fefe9bfeab477501629c44509b1a52063555ee"
source = "https://php.net/distributions/php-7.1.32.tar.gz"
source_sha256 = "6e51a2fc610352438b2a1c40310468a1e2b5baf2fff43be77f9f408a9111590c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.32-linux-x64-cflinuxfs3-644ed4cf.tgz"
version = "7.1.32"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "c9315fce7090db3c26d5823d5ed60a1851864dc44fda5dfe50998862c9d2219b"
source = "https://php.net/distributions/php-7.2.22.tar.gz"
source_sha256 = "6e2ccc77484c27971d4550b7071a57b79bc910bfb2d4a74a57ae2c18b78c3dc7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.22-linux-x64-cflinuxfs3-c9315fce.tgz"
version = "7.2.22"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "7c9e73be2c08c5809307f59533f35f7577265af722836a181014f963e37f62e9"
source = "https://php.net/distributions/php-7.2.23.tar.gz"
source_sha256 = "b32b426c84ff45154d6c11f00aff433bcac831a5c0a09bf0297075eefaea8fcc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.23-linux-x64-cflinuxfs3-7c9e73be.tgz"
version = "7.2.23"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "2e2f589403ee293602c63e231004c84ad6cba541b32eb0ae0256876e9dc43107"
source = "https://php.net/distributions/php-7.3.9.tar.gz"
source_sha256 = "5ecc1b1ad7228ed2e99a970c45358871644fcab1d9fd079a7b129326a7bde42d"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.9-linux-x64-cflinuxfs3-2e2f5894.tgz"
version = "7.3.9"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "479b61280081c8ae05876231f61a55ee9361d5875ca861de7287b50446b1a2a7"
source = "https://php.net/distributions/php-7.3.10.tar.gz"
source_sha256 = "fb670723a9b8fda31c89529f27e0dda289d8af4b6ce9f152c8010876639c0fb4"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.10-linux-x64-cflinuxfs3-479b6128.tgz"
version = "7.3.10"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.1.\\d+"
name = "php"
version_line = "7.1.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-11-30T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.2.\\d+"
name = "php"
version_line = "7.2.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.3.\\d+"
name = "php"
version_line = "7.3.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "5.6.\\d+"
name = "php"
version_line = "5.6.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
