
[buildpack]
id = "org.cloudfoundry.php-dist"
name = "PHP Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml"]
pre_package = "./scripts/build.sh"

[metadata.default-versions]
php-binary = "7.2.*"


[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
source = "https://php.net/distributions/php-5.6.9.tar.gz"
version = "5.6.9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://github.com/pepabo/binary-builder/releases/download/v0.0.1/php-5.6.9-linux-x64.tgz"
sha256 = "777b0067594f20d52845e4f87033933158a5c9d87bbd17c970a47de51a024485"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "21810a8d801b03164ca756ffcd029c89abfbe90fa528716feb6bac193490e351"
source = "https://php.net/distributions/php-7.1.30.tar.gz"
source_sha256 = "a604edf85d5dfc28e6ff3016dad3954c50b93db69afc42295178b4fdf42e026c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.30-linux-x64-cflinuxfs3-21810a8d.tgz"
version = "7.1.30"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "1e7fe73b4969d3922fd6beb7c9f8921d4ffdceb4a1f123e030e95645845a975c"
source = "https://php.net/distributions/php-7.1.31.tar.gz"
source_sha256 = "ea0558735653b9ce63e9cea41dd8f0d0b90dba6c39d39dd9a6aad5cc58b0bdfc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.1.31-linux-x64-cflinuxfs3-1e7fe73b.tgz"
version = "7.1.31"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "e8babad1e120c86eee21ecae0b90e3fe3a844a28a76342f952b97342abf13561"
source = "https://php.net/distributions/php-7.2.20.tar.gz"
source_sha256 = "d1dbf6f299514c9aa55b2995928b798b27c21811a0447f0688993cdf36be0749"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.20-linux-x64-cflinuxfs3-e8babad1.tgz"
version = "7.2.20"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "f5eae7704a2e8fd3eecff85850c6f302ce8e7da73cb75e56ff64a65c60779195"
source = "https://php.net/distributions/php-7.2.21.tar.gz"
source_sha256 = "8327682bee4a8fd2edf5bbfcc393d986b945bec433fc74458d05e766701b313c"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.2.21-linux-x64-cflinuxfs3-f5eae770.tgz"
version = "7.2.21"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "a76a97dcd1d557e38836f6666510a43c4de36b5c4260d165b533cf0336f1209e"
source = "https://php.net/distributions/php-7.3.7.tar.gz"
source_sha256 = "4230bbc862df712b013369de94b131eddea1e5e946a8c5e286b82d441c313328"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.7-linux-x64-cflinuxfs3-a76a97dc.tgz"
version = "7.3.7"

[[metadata.dependencies]]
id = "php-binary"
name = "PHP"
sha256 = "6b2c296c32a8f67606a65fbbbe2fdce302936538bca892d9fb60e4d901a4d592"
source = "https://php.net/distributions/php-7.3.8.tar.gz"
source_sha256 = "31af3eff3337fb70733c9b02a3444c3dae662ecab20aeec7fdc3c42e22071490"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/php/php7-7.3.8-linux-x64-cflinuxfs3-6b2c296c.tgz"
version = "7.3.8"

[[metadata.dependency_deprecation_dates]]
date = 2019-12-01T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.1.\\d+"
name = "php"
version_line = "7.1.x"

[[metadata.dependency_deprecation_dates]]
date = 2020-11-30T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.2.\\d+"
name = "php"
version_line = "7.2.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "7.3.\\d+"
name = "php"
version_line = "7.3.x"

[[metadata.dependency_deprecation_dates]]
date = 2021-12-06T00:00:00Z
link = "http://php.net/supported-versions.php"
match = "5.6.\\d+"
name = "php"
version_line = "5.6.x"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
